import { MigrationInterface, QueryRunner } from "typeorm";

export class ModulesFaJ1790827394918 implements MigrationInterface {
    name = 'ModulesFaJ1790827394918'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."evaluations_sens_enum" AS ENUM('PRODUCTEUR_NOTE_ACHETEUR', 'ACHETEUR_NOTE_PRODUCTEUR')`);
        await queryRunner.query(`CREATE TABLE "evaluations" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "miseEnRelationId" uuid NOT NULL, "auteurId" uuid NOT NULL, "cibleId" uuid NOT NULL, "sens" "public"."evaluations_sens_enum" NOT NULL, "note" smallint NOT NULL, "commentaire" text, "commentaireMasque" boolean NOT NULL DEFAULT false, "dateCreation" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a7fa15a1d9cee100c0fb361d960" UNIQUE ("miseEnRelationId", "sens"), CONSTRAINT "PK_f683b433eba0e6dae7e19b29e29" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_67ed47b8d24159fc702a3212f2" ON "evaluations" ("auteurId") `);
        await queryRunner.query(`CREATE INDEX "IDX_aef5c5faf488f9193ab8822dad" ON "evaluations" ("cibleId") `);
        await queryRunner.query(`CREATE TABLE "langues" ("code" character varying(8) NOT NULL, "libelle" character varying NOT NULL, "actif" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_0896e52de58cf23549ff7fd6c53" PRIMARY KEY ("code"))`);
        await queryRunner.query(`CREATE TYPE "public"."conversations_canal_enum" AS ENUM('BOT', 'AGENT', 'ADMIN')`);
        await queryRunner.query(`CREATE TYPE "public"."conversations_statut_enum" AS ENUM('OUVERTE', 'ESCALADEE_ADMIN', 'CLOTUREE')`);
        await queryRunner.query(`CREATE TYPE "public"."conversations_motifescalade_enum" AS ENUM('LITIGE_PAIEMENT', 'PRODUIT_NON_CONFORME', 'DESACCORD_CONDITIONS', 'AUTRE')`);
        await queryRunner.query(`CREATE TABLE "conversations" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "miseEnRelationId" character varying, "producteurUtilisateurId" character varying, "acheteurUtilisateurId" character varying, "agentUtilisateurId" character varying, "canal" "public"."conversations_canal_enum" NOT NULL DEFAULT 'BOT', "statut" "public"."conversations_statut_enum" NOT NULL DEFAULT 'OUVERTE', "motifEscalade" "public"."conversations_motifescalade_enum", "motifEscaladeDetail" text, "priseEnChargeParAdminId" character varying, "dateEscalade" TIMESTAMP, "dateResolution" TIMESTAMP, "resumeResolution" text, "dateCreation" TIMESTAMP NOT NULL DEFAULT now(), "dateMiseAJour" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ee34f4f7ced4ec8681f26bf04ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_43466d86a5bf556a6851ad9ebc" ON "conversations" ("priseEnChargeParAdminId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7adbe504699810a81ba1b97b3b" ON "conversations" ("statut") `);
        await queryRunner.query(`CREATE INDEX "IDX_a5aeaf61149d5d7bf60516ab94" ON "conversations" ("miseEnRelationId") `);
        await queryRunner.query(`CREATE TYPE "public"."messages_auteurtype_enum" AS ENUM('BOT', 'PRODUCTEUR', 'ACHETEUR', 'AGENT', 'ADMIN')`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "conversationId" uuid NOT NULL, "auteurId" character varying, "auteurType" "public"."messages_auteurtype_enum" NOT NULL, "contenu" text NOT NULL, "dateEnvoi" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e5663ce0c730b2de83445e2fd1" ON "messages" ("conversationId") `);
        await queryRunner.query(`CREATE TYPE "public"."annonces_demande_statut_enum" AS ENUM('OUVERTE', 'EN_NEGOCIATION', 'POURVUE', 'EXPIREE', 'ANNULEE')`);
        await queryRunner.query(`CREATE TABLE "annonces_demande" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "acheteurId" character varying NOT NULL, "produitRecherche" character varying NOT NULL, "quantiteSouhaitee" double precision NOT NULL, "unite" character varying NOT NULL, "prixMaximum" double precision, "region" character varying NOT NULL, "pays" character varying NOT NULL DEFAULT 'Togo', "dateLimiteReponse" TIMESTAMP, "statut" "public"."annonces_demande_statut_enum" NOT NULL DEFAULT 'OUVERTE', "description" text, "masqueeParAdmin" boolean NOT NULL DEFAULT false, "datePublication" TIMESTAMP NOT NULL DEFAULT now(), "dateMiseAJour" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_980dc025e041971182c710367f6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a092dbc6f57f2c0ac5a761dab5" ON "annonces_demande" ("region", "pays") `);
        await queryRunner.query(`CREATE INDEX "IDX_3d0ff2f9160079a7d0fda84190" ON "annonces_demande" ("produitRecherche") `);
        await queryRunner.query(`CREATE INDEX "IDX_1523d08d49438028bc3de23c6b" ON "annonces_demande" ("statut") `);
        await queryRunner.query(`CREATE INDEX "IDX_86059fcd3c411d0bae4fbbe5c8" ON "annonces_demande" ("acheteurId") `);
        await queryRunner.query(`CREATE TYPE "public"."reponses_annonce_demande_statut_enum" AS ENUM('PROPOSEE', 'ACCEPTEE', 'REFUSEE')`);
        await queryRunner.query(`CREATE TABLE "reponses_annonce_demande" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "annonceDemandeId" uuid NOT NULL, "producteurId" character varying NOT NULL, "quantiteProposee" double precision NOT NULL, "prixPropose" double precision, "message" text, "statut" "public"."reponses_annonce_demande_statut_enum" NOT NULL DEFAULT 'PROPOSEE', "dateReponse" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dcecaeca7d6f5cf258a4a098cc8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4efb472d0e28f0b1d9567d4262" ON "reponses_annonce_demande" ("producteurId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3d98e2cf9f5dd6af21eb74493a" ON "reponses_annonce_demande" ("annonceDemandeId") `);
        await queryRunner.query(`CREATE TABLE "pays_reference" ("code" character varying(4) NOT NULL, "nom" character varying NOT NULL, "actif" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_85b8dd798e12481c03870d2c987" UNIQUE ("nom"), CONSTRAINT "PK_b612e7ed09070d1abfe629d6440" PRIMARY KEY ("code"))`);
        await queryRunner.query(`CREATE TYPE "public"."regions_reference_statut_enum" AS ENUM('ACTIVE', 'ARCHIVEE')`);
        await queryRunner.query(`CREATE TABLE "regions_reference" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "paysCode" character varying NOT NULL, "nom" character varying NOT NULL, "statut" "public"."regions_reference_statut_enum" NOT NULL DEFAULT 'ACTIVE', CONSTRAINT "PK_bd178cdf2e2c5e141d1bf4c8d39" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_16eaa97ba8b54e2060d15c4296" ON "regions_reference" ("paysCode") `);
        await queryRunner.query(`CREATE TYPE "public"."prix_reference_statut_enum" AS ENUM('ACTIVE', 'ARCHIVEE')`);
        await queryRunner.query(`CREATE TABLE "prix_reference" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "produit" character varying NOT NULL, "paysCode" character varying NOT NULL, "regionId" character varying, "prixMin" double precision, "prixMax" double precision, "prixMoyen" double precision, "unite" character varying NOT NULL, "statut" "public"."prix_reference_statut_enum" NOT NULL DEFAULT 'ACTIVE', "publieParAdminId" character varying NOT NULL, "versionPrecedenteId" character varying, "datePublication" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_199c87c2fe517678777584fc672" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5b6759faedd1f4f9118305509a" ON "prix_reference" ("statut") `);
        await queryRunner.query(`CREATE INDEX "IDX_b9bd7620e41f375f9aa4dd40bd" ON "prix_reference" ("produit", "paysCode", "regionId") `);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" ADD "origineAnnonceDemandeId" character varying`);
        await queryRunner.query(`ALTER TABLE "utilisateurs" ADD "noteMoyenneRecue" double precision NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "utilisateurs" ADD "nombreEvaluationsRecues" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "utilisateurs" ADD "languePrefereeCode" character varying NOT NULL DEFAULT 'fr'`);
        await queryRunner.query(`ALTER TABLE "activites_exploitation" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "activites_exploitation" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" DROP CONSTRAINT "FK_ce9221534edb8e5575e47665272"`);
        await queryRunner.query(`ALTER TABLE "acheteurs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "acheteurs" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" DROP CONSTRAINT "FK_7d7be9ee17e8517f77840190d81"`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" ALTER COLUMN "annonceId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tableaux_bord_cooperatives" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tableaux_bord_cooperatives" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "tableaux_bord_cooperatives" DROP CONSTRAINT "FK_e0b7a0232d474bee47f5f19e807"`);
        await queryRunner.query(`ALTER TABLE "validations_fiches" DROP CONSTRAINT "FK_c1c46d6745d3187f24d7094b65f"`);
        await queryRunner.query(`ALTER TABLE "cooperatives" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "cooperatives" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "validations_fiches" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "validations_fiches" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "validations_fiches" DROP CONSTRAINT "FK_5e10710246ed5b03a3e2d202f79"`);
        await queryRunner.query(`ALTER TABLE "annonces" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "annonces" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "activites_exploitation" DROP CONSTRAINT "FK_c43569d09259529c86a1ad1315e"`);
        await queryRunner.query(`ALTER TABLE "annonces" DROP CONSTRAINT "FK_f5a9a90808d719b5b482eef4c12"`);
        await queryRunner.query(`ALTER TABLE "exploitations" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "exploitations" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "exploitations" DROP CONSTRAINT "FK_d779b5a7376fb1dde574231ff1f"`);
        await queryRunner.query(`ALTER TABLE "annonces" DROP CONSTRAINT "FK_d858aa21e8e62a8e4e3e297ffc7"`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" DROP CONSTRAINT "FK_d43414ee5d5f4f37d898016fdbe"`);
        await queryRunner.query(`ALTER TABLE "validations_fiches" DROP CONSTRAINT "FK_45cd519fafd52e5a4a164036425"`);
        await queryRunner.query(`ALTER TABLE "producteurs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "producteurs" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "enregistrements_compte" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "enregistrements_compte" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "journaux_synchronisation" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "journaux_synchronisation" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "enregistrements_compte" DROP CONSTRAINT "FK_c61ce3f5d7159e8a075bc63f46d"`);
        await queryRunner.query(`ALTER TABLE "journaux_synchronisation" DROP CONSTRAINT "FK_85efebe43231b68512e74aa28ee"`);
        await queryRunner.query(`ALTER TABLE "agents" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "agents" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_fbdba4e2ac694cf8c9cecf4dc84"`);
        await queryRunner.query(`ALTER TABLE "acheteurs" DROP CONSTRAINT "FK_9b21973b31b0e3e0864a50e98ed"`);
        await queryRunner.query(`ALTER TABLE "producteurs" DROP CONSTRAINT "FK_c5fec7e27c5fae41fa944b3431e"`);
        await queryRunner.query(`ALTER TABLE "cooperatives" DROP CONSTRAINT "FK_4987d9e25c0fda5d4085207f258"`);
        await queryRunner.query(`ALTER TABLE "agents" DROP CONSTRAINT "FK_61643486e3edc623a0eee3063d0"`);
        await queryRunner.query(`ALTER TABLE "journaux_synchronisation" DROP CONSTRAINT "FK_8280980d4dcbc2b1850d1f2c2be"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_8f5adb7d097bce95243ad7e3e57"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_9097c44566a3c1fc5cd5b4132c1"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_d35cb3c13a18e1ea1705b2817b1"`);
        await queryRunner.query(`ALTER TABLE "utilisateurs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "utilisateurs" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "exports_donnees" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "exports_donnees" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "activites_exploitation" ADD CONSTRAINT "FK_c43569d09259529c86a1ad1315e" FOREIGN KEY ("exploitationId") REFERENCES "exploitations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "acheteurs" ADD CONSTRAINT "FK_9b21973b31b0e3e0864a50e98ed" FOREIGN KEY ("utilisateurId") REFERENCES "utilisateurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" ADD CONSTRAINT "FK_7d7be9ee17e8517f77840190d81" FOREIGN KEY ("annonceId") REFERENCES "annonces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" ADD CONSTRAINT "FK_d43414ee5d5f4f37d898016fdbe" FOREIGN KEY ("producteurId") REFERENCES "producteurs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" ADD CONSTRAINT "FK_ce9221534edb8e5575e47665272" FOREIGN KEY ("acheteurId") REFERENCES "acheteurs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tableaux_bord_cooperatives" ADD CONSTRAINT "FK_e0b7a0232d474bee47f5f19e807" FOREIGN KEY ("cooperativeId") REFERENCES "cooperatives"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cooperatives" ADD CONSTRAINT "FK_4987d9e25c0fda5d4085207f258" FOREIGN KEY ("utilisateurId") REFERENCES "utilisateurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "validations_fiches" ADD CONSTRAINT "FK_c1c46d6745d3187f24d7094b65f" FOREIGN KEY ("cooperativeId") REFERENCES "cooperatives"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "validations_fiches" ADD CONSTRAINT "FK_45cd519fafd52e5a4a164036425" FOREIGN KEY ("producteurId") REFERENCES "producteurs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "validations_fiches" ADD CONSTRAINT "FK_5e10710246ed5b03a3e2d202f79" FOREIGN KEY ("annonceId") REFERENCES "annonces"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "annonces" ADD CONSTRAINT "FK_d858aa21e8e62a8e4e3e297ffc7" FOREIGN KEY ("producteurId") REFERENCES "producteurs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "annonces" ADD CONSTRAINT "FK_f5a9a90808d719b5b482eef4c12" FOREIGN KEY ("exploitationId") REFERENCES "exploitations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exploitations" ADD CONSTRAINT "FK_d779b5a7376fb1dde574231ff1f" FOREIGN KEY ("producteurId") REFERENCES "producteurs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "producteurs" ADD CONSTRAINT "FK_c5fec7e27c5fae41fa944b3431e" FOREIGN KEY ("utilisateurId") REFERENCES "utilisateurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enregistrements_compte" ADD CONSTRAINT "FK_c61ce3f5d7159e8a075bc63f46d" FOREIGN KEY ("agentId") REFERENCES "agents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journaux_synchronisation" ADD CONSTRAINT "FK_8280980d4dcbc2b1850d1f2c2be" FOREIGN KEY ("utilisateurId") REFERENCES "utilisateurs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journaux_synchronisation" ADD CONSTRAINT "FK_85efebe43231b68512e74aa28ee" FOREIGN KEY ("agentId") REFERENCES "agents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agents" ADD CONSTRAINT "FK_61643486e3edc623a0eee3063d0" FOREIGN KEY ("utilisateurId") REFERENCES "utilisateurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_8f5adb7d097bce95243ad7e3e57" FOREIGN KEY ("utilisateurId") REFERENCES "utilisateurs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_9097c44566a3c1fc5cd5b4132c1" FOREIGN KEY ("utilisateurId") REFERENCES "utilisateurs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluations" ADD CONSTRAINT "FK_3c2cf7f1d5a90ca1592e980c4f8" FOREIGN KEY ("miseEnRelationId") REFERENCES "mises_en_relation"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluations" ADD CONSTRAINT "FK_67ed47b8d24159fc702a3212f2d" FOREIGN KEY ("auteurId") REFERENCES "utilisateurs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluations" ADD CONSTRAINT "FK_aef5c5faf488f9193ab8822dad5" FOREIGN KEY ("cibleId") REFERENCES "utilisateurs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_e5663ce0c730b2de83445e2fd19" FOREIGN KEY ("conversationId") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reponses_annonce_demande" ADD CONSTRAINT "FK_3d98e2cf9f5dd6af21eb74493a1" FOREIGN KEY ("annonceDemandeId") REFERENCES "annonces_demande"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_d35cb3c13a18e1ea1705b2817b1" FOREIGN KEY ("userId") REFERENCES "utilisateurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_fbdba4e2ac694cf8c9cecf4dc84" FOREIGN KEY ("userId") REFERENCES "utilisateurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_fbdba4e2ac694cf8c9cecf4dc84"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_d35cb3c13a18e1ea1705b2817b1"`);
        await queryRunner.query(`ALTER TABLE "reponses_annonce_demande" DROP CONSTRAINT "FK_3d98e2cf9f5dd6af21eb74493a1"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_e5663ce0c730b2de83445e2fd19"`);
        await queryRunner.query(`ALTER TABLE "evaluations" DROP CONSTRAINT "FK_aef5c5faf488f9193ab8822dad5"`);
        await queryRunner.query(`ALTER TABLE "evaluations" DROP CONSTRAINT "FK_67ed47b8d24159fc702a3212f2d"`);
        await queryRunner.query(`ALTER TABLE "evaluations" DROP CONSTRAINT "FK_3c2cf7f1d5a90ca1592e980c4f8"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_9097c44566a3c1fc5cd5b4132c1"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_8f5adb7d097bce95243ad7e3e57"`);
        await queryRunner.query(`ALTER TABLE "agents" DROP CONSTRAINT "FK_61643486e3edc623a0eee3063d0"`);
        await queryRunner.query(`ALTER TABLE "journaux_synchronisation" DROP CONSTRAINT "FK_85efebe43231b68512e74aa28ee"`);
        await queryRunner.query(`ALTER TABLE "journaux_synchronisation" DROP CONSTRAINT "FK_8280980d4dcbc2b1850d1f2c2be"`);
        await queryRunner.query(`ALTER TABLE "enregistrements_compte" DROP CONSTRAINT "FK_c61ce3f5d7159e8a075bc63f46d"`);
        await queryRunner.query(`ALTER TABLE "producteurs" DROP CONSTRAINT "FK_c5fec7e27c5fae41fa944b3431e"`);
        await queryRunner.query(`ALTER TABLE "exploitations" DROP CONSTRAINT "FK_d779b5a7376fb1dde574231ff1f"`);
        await queryRunner.query(`ALTER TABLE "annonces" DROP CONSTRAINT "FK_f5a9a90808d719b5b482eef4c12"`);
        await queryRunner.query(`ALTER TABLE "annonces" DROP CONSTRAINT "FK_d858aa21e8e62a8e4e3e297ffc7"`);
        await queryRunner.query(`ALTER TABLE "validations_fiches" DROP CONSTRAINT "FK_5e10710246ed5b03a3e2d202f79"`);
        await queryRunner.query(`ALTER TABLE "validations_fiches" DROP CONSTRAINT "FK_45cd519fafd52e5a4a164036425"`);
        await queryRunner.query(`ALTER TABLE "validations_fiches" DROP CONSTRAINT "FK_c1c46d6745d3187f24d7094b65f"`);
        await queryRunner.query(`ALTER TABLE "cooperatives" DROP CONSTRAINT "FK_4987d9e25c0fda5d4085207f258"`);
        await queryRunner.query(`ALTER TABLE "tableaux_bord_cooperatives" DROP CONSTRAINT "FK_e0b7a0232d474bee47f5f19e807"`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" DROP CONSTRAINT "FK_ce9221534edb8e5575e47665272"`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" DROP CONSTRAINT "FK_d43414ee5d5f4f37d898016fdbe"`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" DROP CONSTRAINT "FK_7d7be9ee17e8517f77840190d81"`);
        await queryRunner.query(`ALTER TABLE "acheteurs" DROP CONSTRAINT "FK_9b21973b31b0e3e0864a50e98ed"`);
        await queryRunner.query(`ALTER TABLE "activites_exploitation" DROP CONSTRAINT "FK_c43569d09259529c86a1ad1315e"`);
        await queryRunner.query(`ALTER TABLE "exports_donnees" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "exports_donnees" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "utilisateurs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "utilisateurs" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_d35cb3c13a18e1ea1705b2817b1" FOREIGN KEY ("userId") REFERENCES "utilisateurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_9097c44566a3c1fc5cd5b4132c1" FOREIGN KEY ("utilisateurId") REFERENCES "utilisateurs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_8f5adb7d097bce95243ad7e3e57" FOREIGN KEY ("utilisateurId") REFERENCES "utilisateurs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journaux_synchronisation" ADD CONSTRAINT "FK_8280980d4dcbc2b1850d1f2c2be" FOREIGN KEY ("utilisateurId") REFERENCES "utilisateurs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agents" ADD CONSTRAINT "FK_61643486e3edc623a0eee3063d0" FOREIGN KEY ("utilisateurId") REFERENCES "utilisateurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cooperatives" ADD CONSTRAINT "FK_4987d9e25c0fda5d4085207f258" FOREIGN KEY ("utilisateurId") REFERENCES "utilisateurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "producteurs" ADD CONSTRAINT "FK_c5fec7e27c5fae41fa944b3431e" FOREIGN KEY ("utilisateurId") REFERENCES "utilisateurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "acheteurs" ADD CONSTRAINT "FK_9b21973b31b0e3e0864a50e98ed" FOREIGN KEY ("utilisateurId") REFERENCES "utilisateurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_fbdba4e2ac694cf8c9cecf4dc84" FOREIGN KEY ("userId") REFERENCES "utilisateurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "agents" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "agents" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "journaux_synchronisation" ADD CONSTRAINT "FK_85efebe43231b68512e74aa28ee" FOREIGN KEY ("agentId") REFERENCES "agents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enregistrements_compte" ADD CONSTRAINT "FK_c61ce3f5d7159e8a075bc63f46d" FOREIGN KEY ("agentId") REFERENCES "agents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journaux_synchronisation" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "journaux_synchronisation" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "enregistrements_compte" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "enregistrements_compte" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "producteurs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "producteurs" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "validations_fiches" ADD CONSTRAINT "FK_45cd519fafd52e5a4a164036425" FOREIGN KEY ("producteurId") REFERENCES "producteurs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" ADD CONSTRAINT "FK_d43414ee5d5f4f37d898016fdbe" FOREIGN KEY ("producteurId") REFERENCES "producteurs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "annonces" ADD CONSTRAINT "FK_d858aa21e8e62a8e4e3e297ffc7" FOREIGN KEY ("producteurId") REFERENCES "producteurs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exploitations" ADD CONSTRAINT "FK_d779b5a7376fb1dde574231ff1f" FOREIGN KEY ("producteurId") REFERENCES "producteurs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exploitations" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "exploitations" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "annonces" ADD CONSTRAINT "FK_f5a9a90808d719b5b482eef4c12" FOREIGN KEY ("exploitationId") REFERENCES "exploitations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activites_exploitation" ADD CONSTRAINT "FK_c43569d09259529c86a1ad1315e" FOREIGN KEY ("exploitationId") REFERENCES "exploitations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "annonces" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "annonces" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "validations_fiches" ADD CONSTRAINT "FK_5e10710246ed5b03a3e2d202f79" FOREIGN KEY ("annonceId") REFERENCES "annonces"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "validations_fiches" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "validations_fiches" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "cooperatives" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "cooperatives" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "validations_fiches" ADD CONSTRAINT "FK_c1c46d6745d3187f24d7094b65f" FOREIGN KEY ("cooperativeId") REFERENCES "cooperatives"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tableaux_bord_cooperatives" ADD CONSTRAINT "FK_e0b7a0232d474bee47f5f19e807" FOREIGN KEY ("cooperativeId") REFERENCES "cooperatives"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tableaux_bord_cooperatives" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tableaux_bord_cooperatives" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" ALTER COLUMN "annonceId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" ADD CONSTRAINT "FK_7d7be9ee17e8517f77840190d81" FOREIGN KEY ("annonceId") REFERENCES "annonces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "acheteurs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "acheteurs" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" ADD CONSTRAINT "FK_ce9221534edb8e5575e47665272" FOREIGN KEY ("acheteurId") REFERENCES "acheteurs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activites_exploitation" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "activites_exploitation" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "utilisateurs" DROP COLUMN "languePrefereeCode"`);
        await queryRunner.query(`ALTER TABLE "utilisateurs" DROP COLUMN "nombreEvaluationsRecues"`);
        await queryRunner.query(`ALTER TABLE "utilisateurs" DROP COLUMN "noteMoyenneRecue"`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" DROP COLUMN "origineAnnonceDemandeId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b9bd7620e41f375f9aa4dd40bd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b6759faedd1f4f9118305509a"`);
        await queryRunner.query(`DROP TABLE "prix_reference"`);
        await queryRunner.query(`DROP TYPE "public"."prix_reference_statut_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_16eaa97ba8b54e2060d15c4296"`);
        await queryRunner.query(`DROP TABLE "regions_reference"`);
        await queryRunner.query(`DROP TYPE "public"."regions_reference_statut_enum"`);
        await queryRunner.query(`DROP TABLE "pays_reference"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d98e2cf9f5dd6af21eb74493a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4efb472d0e28f0b1d9567d4262"`);
        await queryRunner.query(`DROP TABLE "reponses_annonce_demande"`);
        await queryRunner.query(`DROP TYPE "public"."reponses_annonce_demande_statut_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_86059fcd3c411d0bae4fbbe5c8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1523d08d49438028bc3de23c6b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d0ff2f9160079a7d0fda84190"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a092dbc6f57f2c0ac5a761dab5"`);
        await queryRunner.query(`DROP TABLE "annonces_demande"`);
        await queryRunner.query(`DROP TYPE "public"."annonces_demande_statut_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5663ce0c730b2de83445e2fd1"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TYPE "public"."messages_auteurtype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a5aeaf61149d5d7bf60516ab94"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7adbe504699810a81ba1b97b3b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_43466d86a5bf556a6851ad9ebc"`);
        await queryRunner.query(`DROP TABLE "conversations"`);
        await queryRunner.query(`DROP TYPE "public"."conversations_motifescalade_enum"`);
        await queryRunner.query(`DROP TYPE "public"."conversations_statut_enum"`);
        await queryRunner.query(`DROP TYPE "public"."conversations_canal_enum"`);
        await queryRunner.query(`DROP TABLE "langues"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aef5c5faf488f9193ab8822dad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_67ed47b8d24159fc702a3212f2"`);
        await queryRunner.query(`DROP TABLE "evaluations"`);
        await queryRunner.query(`DROP TYPE "public"."evaluations_sens_enum"`);
    }

}
