import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1790653187258 implements MigrationInterface {
    name = 'InitialSchema1790653187258'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "activites_exploitation" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "exploitationId" uuid NOT NULL, "type" character varying NOT NULL, "usedArea" double precision NOT NULL, "estimatedYield" double precision, "productionPeriod" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_13aff2c0cc85626bade42500bcd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c43569d09259529c86a1ad1315" ON "activites_exploitation" ("exploitationId") `);
        await queryRunner.query(`CREATE TABLE "acheteurs" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "utilisateurId" uuid NOT NULL, "typeSociete" character varying NOT NULL, "nomSociete" character varying, "adresseSociete" character varying, "region" character varying, "pays" character varying NOT NULL DEFAULT 'Togo', "telephone" character varying, "email" character varying, "dateCreation" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9b21973b31b0e3e0864a50e98ed" UNIQUE ("utilisateurId"), CONSTRAINT "REL_9b21973b31b0e3e0864a50e98e" UNIQUE ("utilisateurId"), CONSTRAINT "PK_6e80e97bd521260534168895252" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9b21973b31b0e3e0864a50e98e" ON "acheteurs" ("utilisateurId") `);
        await queryRunner.query(`CREATE TYPE "public"."mises_en_relation_statut_enum" AS ENUM('EN_ATTENTE', 'ACCEPTEE', 'REJETEE', 'FINALISEE', 'ECHAPPEE')`);
        await queryRunner.query(`CREATE TABLE "mises_en_relation" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "annonceId" uuid NOT NULL, "producteurId" uuid NOT NULL, "acheteurId" uuid NOT NULL, "statut" "public"."mises_en_relation_statut_enum" NOT NULL DEFAULT 'EN_ATTENTE', "montantNegociation" double precision, "quantiteNegociee" double precision, "dateContactInitial" TIMESTAMP NOT NULL DEFAULT now(), "dateAcceptation" TIMESTAMP, "dateRejection" TIMESTAMP, "dateFinalization" TIMESTAMP, "commentaires" character varying, CONSTRAINT "PK_09fe0dbbfd68e34bd9b6ce53fa3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eb65ea2dd19b72aadace3044fd" ON "mises_en_relation" ("statut") `);
        await queryRunner.query(`CREATE INDEX "IDX_ce9221534edb8e5575e4766527" ON "mises_en_relation" ("acheteurId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d43414ee5d5f4f37d898016fdb" ON "mises_en_relation" ("producteurId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7d7be9ee17e8517f77840190d8" ON "mises_en_relation" ("annonceId") `);
        await queryRunner.query(`CREATE TABLE "tableaux_bord_cooperatives" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "cooperativeId" uuid NOT NULL, "totalProducteurs" integer NOT NULL DEFAULT '0', "totalExploitations" integer NOT NULL DEFAULT '0', "totalAnnonces" integer NOT NULL DEFAULT '0', "totalValidations" integer NOT NULL DEFAULT '0', "validationsEnCours" integer NOT NULL DEFAULT '0', "dateModification" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e0b7a0232d474bee47f5f19e807" UNIQUE ("cooperativeId"), CONSTRAINT "REL_e0b7a0232d474bee47f5f19e80" UNIQUE ("cooperativeId"), CONSTRAINT "PK_5918e2dff7a0d8d088eeda2f6a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e0b7a0232d474bee47f5f19e80" ON "tableaux_bord_cooperatives" ("cooperativeId") `);
        await queryRunner.query(`CREATE TABLE "cooperatives" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "utilisateurId" uuid NOT NULL, "nomOfficial" character varying NOT NULL, "numeroRegistration" character varying NOT NULL, "adresse" character varying NOT NULL, "region" character varying NOT NULL, "telephone" character varying NOT NULL, "email" character varying NOT NULL, "nombreMembres" integer NOT NULL DEFAULT '0', "dateCreation" TIMESTAMP NOT NULL DEFAULT now(), "dateModification" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4987d9e25c0fda5d4085207f258" UNIQUE ("utilisateurId"), CONSTRAINT "UQ_be7340937a9f0c8c49b2fc97781" UNIQUE ("numeroRegistration"), CONSTRAINT "REL_4987d9e25c0fda5d4085207f25" UNIQUE ("utilisateurId"), CONSTRAINT "PK_52fc93ab8869e3f71c46601fe9b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2c7a7d6d960bd8344617164dd0" ON "cooperatives" ("region") `);
        await queryRunner.query(`CREATE INDEX "IDX_4987d9e25c0fda5d4085207f25" ON "cooperatives" ("utilisateurId") `);
        await queryRunner.query(`CREATE TABLE "validations_fiches" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "cooperativeId" uuid NOT NULL, "producteurId" uuid NOT NULL, "annonceId" uuid, "statut" character varying NOT NULL DEFAULT 'EN_ATTENTE', "commentaires" character varying, "dateValidation" TIMESTAMP, "dateCreation" TIMESTAMP NOT NULL DEFAULT now(), "dateModification" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f4f8d55577d68fce28ef867ac53" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ae6e0e5110b8085d7cbf82d317" ON "validations_fiches" ("statut") `);
        await queryRunner.query(`CREATE INDEX "IDX_45cd519fafd52e5a4a16403642" ON "validations_fiches" ("producteurId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c1c46d6745d3187f24d7094b65" ON "validations_fiches" ("cooperativeId") `);
        await queryRunner.query(`CREATE TYPE "public"."annonces_status_enum" AS ENUM('PUBLIEE', 'VENDUE', 'ANNULEE', 'EN_ATTENTE_VALIDATION')`);
        await queryRunner.query(`CREATE TABLE "annonces" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "producerId" character varying NOT NULL, "exploitationId" uuid, "title" character varying NOT NULL, "description" character varying NOT NULL, "productionType" character varying NOT NULL, "availableQuantity" double precision NOT NULL, "unit" character varying NOT NULL, "unitPrice" double precision NOT NULL, "currency" character varying NOT NULL DEFAULT 'XOF', "status" "public"."annonces_status_enum" NOT NULL DEFAULT 'EN_ATTENTE_VALIDATION', "publicationDate" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "dateExpiration" TIMESTAMP, "photos" text array NOT NULL DEFAULT '{}', "producteurId" uuid, CONSTRAINT "PK_6f27d25a69c00d8b1795919635d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b43ea95df4570d0f4f719f4ac1" ON "annonces" ("publicationDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_800dcc4afcad41ac18cd71add9" ON "annonces" ("productionType") `);
        await queryRunner.query(`CREATE INDEX "IDX_81ccb763336cf43c58cbadb20d" ON "annonces" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_317c1c908c017c011f4e19cac4" ON "annonces" ("producerId") `);
        await queryRunner.query(`CREATE TYPE "public"."exploitations_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'SUSPENDUE', 'EN_ATTENTE')`);
        await queryRunner.query(`CREATE TABLE "exploitations" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "producerId" character varying NOT NULL, "name" character varying NOT NULL, "totalArea" double precision NOT NULL, "exploitationType" text array NOT NULL, "status" "public"."exploitations_status_enum" NOT NULL DEFAULT 'EN_ATTENTE', "address" character varying NOT NULL, "geolocation" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "generalDescription" character varying, "producteurId" uuid, CONSTRAINT "PK_6a0a0a176f4840a109896e4aee0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_99b364aba8c5ab1d6ab713b717" ON "exploitations" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3d2d8bc234df52a46c6ab5b8f1" ON "exploitations" ("producerId") `);
        await queryRunner.query(`CREATE TABLE "producteurs" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "userId" character varying NOT NULL, "identificationNumber" character varying, "identificationType" character varying, "identificationIssueDate" TIMESTAMP, "address" character varying NOT NULL, "postalCode" character varying, "city" character varying NOT NULL, "region" character varying NOT NULL, "pays" character varying NOT NULL DEFAULT 'Togo', "geolocation" character varying, "yearsOfExperience" integer NOT NULL, "registrationDate" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "utilisateurId" uuid, CONSTRAINT "UQ_19e85cc7ad03b8b91e7dbe9f4e8" UNIQUE ("userId"), CONSTRAINT "REL_c5fec7e27c5fae41fa944b3431" UNIQUE ("utilisateurId"), CONSTRAINT "PK_21a6b36496214eab67e8c418f6f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_19e85cc7ad03b8b91e7dbe9f4e" ON "producteurs" ("userId") `);
        await queryRunner.query(`CREATE TABLE "enregistrements_compte" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "agentId" uuid NOT NULL, "typeSousacription" character varying NOT NULL, "nombreAccounts" integer NOT NULL DEFAULT '1', "dateEnregistrement" TIMESTAMP NOT NULL DEFAULT now(), "details" character varying, CONSTRAINT "PK_95f1b6f89f5a0acb0c2e32b3bdd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c61ce3f5d7159e8a075bc63f46" ON "enregistrements_compte" ("agentId") `);
        await queryRunner.query(`CREATE TYPE "public"."journaux_synchronisation_statut_enum" AS ENUM('EN_ATTENTE', 'OK', 'ECHEC')`);
        await queryRunner.query(`CREATE TABLE "journaux_synchronisation" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "utilisateurId" uuid NOT NULL, "agentId" uuid NOT NULL, "idClientGenere" character varying NOT NULL, "nombreEnregistrements" integer NOT NULL, "statut" "public"."journaux_synchronisation_statut_enum" NOT NULL DEFAULT 'EN_ATTENTE', "dateCreationClient" TIMESTAMP NOT NULL, "dateSynchronisation" TIMESTAMP NOT NULL DEFAULT now(), "payloadOperations" character varying NOT NULL, "messageErreur" character varying, "dateRetry" TIMESTAMP, CONSTRAINT "UQ_5e2bc42312ab5c8b0e29f0edfdd" UNIQUE ("idClientGenere"), CONSTRAINT "PK_d9c39b27b35b51a4128ac05e568" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5e2bc42312ab5c8b0e29f0edfd" ON "journaux_synchronisation" ("idClientGenere") `);
        await queryRunner.query(`CREATE INDEX "IDX_1d87030cbdf61dd6a74d87d1ef" ON "journaux_synchronisation" ("statut") `);
        await queryRunner.query(`CREATE INDEX "IDX_85efebe43231b68512e74aa28e" ON "journaux_synchronisation" ("agentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8280980d4dcbc2b1850d1f2c2b" ON "journaux_synchronisation" ("utilisateurId") `);
        await queryRunner.query(`CREATE TABLE "agents" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "utilisateurId" uuid NOT NULL, "numeroIdentifiant" character varying NOT NULL, "zone" character varying NOT NULL, "dateAffectation" TIMESTAMP NOT NULL DEFAULT now(), "statut" character varying NOT NULL DEFAULT 'ACTIF', "derniereConnexion" TIMESTAMP, "dateCreation" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_61643486e3edc623a0eee3063d0" UNIQUE ("utilisateurId"), CONSTRAINT "UQ_83d51097075971a6a73bc8ea909" UNIQUE ("numeroIdentifiant"), CONSTRAINT "REL_61643486e3edc623a0eee3063d" UNIQUE ("utilisateurId"), CONSTRAINT "PK_9c653f28ae19c5884d5baf6a1d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ab0c6cef42ab7886f4c324e85b" ON "agents" ("zone") `);
        await queryRunner.query(`CREATE INDEX "IDX_61643486e3edc623a0eee3063d" ON "agents" ("utilisateurId") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('SMS', 'VOCAL', 'USSD', 'EMAIL', 'PUSH')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "utilisateurId" uuid NOT NULL, "type" "public"."notifications_type_enum" NOT NULL, "titre" character varying NOT NULL, "contenu" character varying NOT NULL, "dateEnvoi" TIMESTAMP, "dateCreation" TIMESTAMP NOT NULL DEFAULT now(), "lu" boolean NOT NULL DEFAULT false, "dateLecture" TIMESTAMP, "statut" character varying NOT NULL DEFAULT 'EN_ATTENTE', CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_aef1c7aef3725068e5540f8f00" ON "notifications" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_e52cbf86d17b46f1dc80d9185b" ON "notifications" ("statut") `);
        await queryRunner.query(`CREATE INDEX "IDX_8f5adb7d097bce95243ad7e3e5" ON "notifications" ("utilisateurId") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "utilisateurId" uuid NOT NULL, "action" character varying NOT NULL, "entite" character varying NOT NULL, "entiteId" character varying NOT NULL, "anciennesValeurs" character varying, "nouvellesValeurs" character varying, "ipAdresse" character varying, "userAgent" character varying, "dateCreation" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6bac423b022c9760a3fa7f403b" ON "audit_logs" ("dateCreation") `);
        await queryRunner.query(`CREATE INDEX "IDX_1d08be4a4e9c6eb8fcad0f1d19" ON "audit_logs" ("entite") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_9097c44566a3c1fc5cd5b4132c" ON "audit_logs" ("utilisateurId") `);
        await queryRunner.query(`CREATE TYPE "public"."utilisateurs_role_enum" AS ENUM('PRODUCTEUR', 'AGENT', 'COOPERATIVE', 'ACHETEUR', 'ADMIN')`);
        await queryRunner.query(`CREATE TABLE "utilisateurs" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "email" character varying NOT NULL, "passwordHash" character varying NOT NULL, "phone" character varying, "lastName" character varying NOT NULL, "firstName" character varying NOT NULL, "photo" character varying, "role" "public"."utilisateurs_role_enum" NOT NULL, "accessChannelPreferences" text array NOT NULL DEFAULT '{MOBILE_APP,WEB}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "active" boolean NOT NULL DEFAULT true, "hasSmartphone" boolean NOT NULL DEFAULT true, "mustChangePassword" boolean NOT NULL DEFAULT false, "createdByAgentId" uuid, CONSTRAINT "UQ_6b14325a486fe68d16aa889e4dc" UNIQUE ("email"), CONSTRAINT "UQ_20f8a7753c8859ff4a4ccd78505" UNIQUE ("phone"), CONSTRAINT "PK_d3c39b551c51a0bdc76e07b9197" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cc6b96ba6911515323091fe622" ON "utilisateurs" ("createdByAgentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ceb8ddfd4ec97d405837e10c11" ON "utilisateurs" ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_20f8a7753c8859ff4a4ccd7850" ON "utilisateurs" ("phone") `);
        await queryRunner.query(`CREATE INDEX "IDX_6b14325a486fe68d16aa889e4d" ON "utilisateurs" ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."exports_donnees_type_enum" AS ENUM('CSV', 'EXCEL', 'PDF')`);
        await queryRunner.query(`CREATE TABLE "exports_donnees" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "utilisateurId" character varying NOT NULL, "type" "public"."exports_donnees_type_enum" NOT NULL, "donnees" character varying NOT NULL, "lienTelechargement" character varying, "dateCreation" TIMESTAMP NOT NULL DEFAULT now(), "dateExpiration" TIMESTAMP NOT NULL, "statut" character varying NOT NULL DEFAULT 'EN_PREPARATION', CONSTRAINT "PK_df397aceb301d72cf2b86165a91" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6ac85a9d120da7da0461a46df2" ON "exports_donnees" ("statut") `);
        await queryRunner.query(`CREATE INDEX "IDX_d060a49c7f2acc9ea92bc89269" ON "exports_donnees" ("utilisateurId") `);
        await queryRunner.query(`CREATE TYPE "public"."subscription_features_featurekey_enum" AS ENUM('MAX_ANNOUNCEMENTS', 'MAX_SMS_PER_MONTH', 'MAX_RELATIONSHIPS_PER_MONTH', 'PRICE_HISTORY_DAYS', 'MATURITY_REMINDERS', 'PRICE_REMINDERS', 'WHATSAPP_ENABLED', 'CALLS_ENABLED', 'API_ACCESS', 'ADVANCED_FILTERS', 'EXPORT_DATA', 'SUPPORT_PRIORITY')`);
        await queryRunner.query(`CREATE TABLE "subscription_features" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "subscriptionId" uuid NOT NULL, "featureKey" "public"."subscription_features_featurekey_enum" NOT NULL, "featureValue" integer, "description" text, "isEnabled" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ccc43bd8450ac408d5b4d38379f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subscription_usages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "subscriptionId" uuid NOT NULL, "feature" character varying NOT NULL, "usedCount" integer NOT NULL DEFAULT '0', "monthlyLimit" integer, "monthStartDate" TIMESTAMP NOT NULL, "monthEndDate" TIMESTAMP NOT NULL, "isOverLimit" boolean NOT NULL DEFAULT false, "autoReset" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_613da5d4a049ecafda8e4688dad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_05c8ddf3d99da9c01b7bdd2ecc" ON "subscription_usages" ("subscriptionId", "monthStartDate") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_paymentmethod_enum" AS ENUM('MOBILE_MONEY', 'CARD', 'BANK_TRANSFER', 'CRYPTO', 'CASH')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "subscriptionId" uuid NOT NULL, "userId" uuid NOT NULL, "amount" numeric(12,2) NOT NULL, "currency" character varying NOT NULL DEFAULT 'FCFA', "paymentMethod" "public"."payments_paymentmethod_enum" NOT NULL, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'PENDING', "transactionId" character varying, "reference" character varying, "description" text, "providerResponse" jsonb, "errorMessage" text, "retryCount" integer NOT NULL DEFAULT '0', "nextRetryDate" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "paidAt" TIMESTAMP, CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_32b41cdb985a296213e9a928b5" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c39d78e8744809ece8ca95730e" ON "payments" ("transactionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1c9b5fb7b9f38cccddd7c5761b" ON "payments" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_dd1869507a16757b4f1769220a" ON "payments" ("subscriptionId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_type_enum" AS ENUM('PRODUCTEUR', 'ACHETEUR')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_tier_enum" AS ENUM('GRATUIT', 'STANDARD', 'PREMIUM')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('ACTIVE', 'PAUSED', 'CANCELLED', 'EXPIRED', 'PENDING_PAYMENT')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "type" "public"."subscriptions_type_enum" NOT NULL DEFAULT 'PRODUCTEUR', "tier" "public"."subscriptions_tier_enum" NOT NULL DEFAULT 'GRATUIT', "status" "public"."subscriptions_status_enum" NOT NULL DEFAULT 'ACTIVE', "startDate" TIMESTAMP NOT NULL, "endDate" TIMESTAMP, "renewalDate" TIMESTAMP, "autoRenew" boolean NOT NULL DEFAULT true, "amount" numeric(12,2), "currency" character varying NOT NULL DEFAULT 'FCFA', "billingCycleDays" integer NOT NULL DEFAULT '1', "renewalCount" integer NOT NULL DEFAULT '0', "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_10349f5b8d6102567c05cc1da2" ON "subscriptions" ("renewalDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_ca1806bbc03217f7cc6a55acab" ON "subscriptions" ("tier") `);
        await queryRunner.query(`CREATE INDEX "IDX_6ccf973355b70645eff37774de" ON "subscriptions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_5b2dfa8aac35d4e39389268935" ON "subscriptions" ("userId", "type") `);
        await queryRunner.query(`CREATE TYPE "public"."subscription_plans_type_enum" AS ENUM('PRODUCTEUR', 'ACHETEUR')`);
        await queryRunner.query(`CREATE TABLE "subscription_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."subscription_plans_type_enum" NOT NULL, "tier" character varying NOT NULL, "price" numeric(12,2) NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'FCFA', "billingCycleDays" integer, "features" jsonb NOT NULL DEFAULT '{}', "isActive" boolean NOT NULL DEFAULT true, "displayOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9ab8fe6918451ab3d0a4fb6bb0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a0b884a3a9964aef2cd41fda60" ON "subscription_plans" ("type") `);
        await queryRunner.query(`ALTER TABLE "activites_exploitation" ADD CONSTRAINT "FK_c43569d09259529c86a1ad1315e" FOREIGN KEY ("exploitationId") REFERENCES "exploitations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "acheteurs" ADD CONSTRAINT "FK_9b21973b31b0e3e0864a50e98ed" FOREIGN KEY ("utilisateurId") REFERENCES "utilisateurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" ADD CONSTRAINT "FK_7d7be9ee17e8517f77840190d81" FOREIGN KEY ("annonceId") REFERENCES "annonces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" ADD CONSTRAINT "FK_d43414ee5d5f4f37d898016fdbe" FOREIGN KEY ("producteurId") REFERENCES "producteurs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" ADD CONSTRAINT "FK_ce9221534edb8e5575e47665272" FOREIGN KEY ("acheteurId") REFERENCES "acheteurs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tableaux_bord_cooperatives" ADD CONSTRAINT "FK_e0b7a0232d474bee47f5f19e807" FOREIGN KEY ("cooperativeId") REFERENCES "cooperatives"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cooperatives" ADD CONSTRAINT "FK_4987d9e25c0fda5d4085207f258" FOREIGN KEY ("utilisateurId") REFERENCES "utilisateurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "validations_fiches" ADD CONSTRAINT "FK_c1c46d6745d3187f24d7094b65f" FOREIGN KEY ("cooperativeId") REFERENCES "cooperatives"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "validations_fiches" ADD CONSTRAINT "FK_45cd519fafd52e5a4a164036425" FOREIGN KEY ("producteurId") REFERENCES "producteurs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "validations_fiches" ADD CONSTRAINT "FK_5e10710246ed5b03a3e2d202f79" FOREIGN KEY ("annonceId") REFERENCES "annonces"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "annonces" ADD CONSTRAINT "FK_d858aa21e8e62a8e4e3e297ffc7" FOREIGN KEY ("producteurId") REFERENCES "producteurs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "annonces" ADD CONSTRAINT "FK_f5a9a90808d719b5b482eef4c12" FOREIGN KEY ("exploitationId") REFERENCES "exploitations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exploitations" ADD CONSTRAINT "FK_d779b5a7376fb1dde574231ff1f" FOREIGN KEY ("producteurId") REFERENCES "producteurs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "producteurs" ADD CONSTRAINT "FK_c5fec7e27c5fae41fa944b3431e" FOREIGN KEY ("utilisateurId") REFERENCES "utilisateurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enregistrements_compte" ADD CONSTRAINT "FK_c61ce3f5d7159e8a075bc63f46d" FOREIGN KEY ("agentId") REFERENCES "agents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journaux_synchronisation" ADD CONSTRAINT "FK_8280980d4dcbc2b1850d1f2c2be" FOREIGN KEY ("utilisateurId") REFERENCES "utilisateurs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journaux_synchronisation" ADD CONSTRAINT "FK_85efebe43231b68512e74aa28ee" FOREIGN KEY ("agentId") REFERENCES "agents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agents" ADD CONSTRAINT "FK_61643486e3edc623a0eee3063d0" FOREIGN KEY ("utilisateurId") REFERENCES "utilisateurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_8f5adb7d097bce95243ad7e3e57" FOREIGN KEY ("utilisateurId") REFERENCES "utilisateurs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_9097c44566a3c1fc5cd5b4132c1" FOREIGN KEY ("utilisateurId") REFERENCES "utilisateurs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_features" ADD CONSTRAINT "FK_b56a0bc04ebfda94a2620496fa0" FOREIGN KEY ("subscriptionId") REFERENCES "subscriptions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_usages" ADD CONSTRAINT "FK_8427aedab2911739ca3eef3b6cd" FOREIGN KEY ("subscriptionId") REFERENCES "subscriptions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_2017d0cbfdbfec6b1b388e6aa08" FOREIGN KEY ("subscriptionId") REFERENCES "subscriptions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_d35cb3c13a18e1ea1705b2817b1" FOREIGN KEY ("userId") REFERENCES "utilisateurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_fbdba4e2ac694cf8c9cecf4dc84" FOREIGN KEY ("userId") REFERENCES "utilisateurs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_fbdba4e2ac694cf8c9cecf4dc84"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_d35cb3c13a18e1ea1705b2817b1"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_2017d0cbfdbfec6b1b388e6aa08"`);
        await queryRunner.query(`ALTER TABLE "subscription_usages" DROP CONSTRAINT "FK_8427aedab2911739ca3eef3b6cd"`);
        await queryRunner.query(`ALTER TABLE "subscription_features" DROP CONSTRAINT "FK_b56a0bc04ebfda94a2620496fa0"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_9097c44566a3c1fc5cd5b4132c1"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_8f5adb7d097bce95243ad7e3e57"`);
        await queryRunner.query(`ALTER TABLE "agents" DROP CONSTRAINT "FK_61643486e3edc623a0eee3063d0"`);
        await queryRunner.query(`ALTER TABLE "journaux_synchronisation" DROP CONSTRAINT "FK_85efebe43231b68512e74aa28ee"`);
        await queryRunner.query(`ALTER TABLE "journaux_synchronisation" DROP CONSTRAINT "FK_8280980d4dcbc2b1850d1f2c2be"`);
        await queryRunner.query(`ALTER TABLE "enregistrements_compte" DROP CONSTRAINT "FK_c61ce3f5d7159e8a075bc63f46d"`);
        await queryRunner.query(`ALTER TABLE "producteurs" DROP CONSTRAINT "FK_c5fec7e27c5fae41fa944b3431e"`);
        await queryRunner.query(`ALTER TABLE "exploitations" DROP CONSTRAINT "FK_d779b5a7376fb1dde574231ff1f"`);
        await queryRunner.query(`ALTER TABLE "annonces" DROP CONSTRAINT "FK_f5a9a90808d719b5b482eef4c12"`);
        await queryRunner.query(`ALTER TABLE "annonces" DROP CONSTRAINT "FK_d858aa21e8e62a8e4e3e297ffc7"`);
        await queryRunner.query(`ALTER TABLE "validations_fiches" DROP CONSTRAINT "FK_5e10710246ed5b03a3e2d202f79"`);
        await queryRunner.query(`ALTER TABLE "validations_fiches" DROP CONSTRAINT "FK_45cd519fafd52e5a4a164036425"`);
        await queryRunner.query(`ALTER TABLE "validations_fiches" DROP CONSTRAINT "FK_c1c46d6745d3187f24d7094b65f"`);
        await queryRunner.query(`ALTER TABLE "cooperatives" DROP CONSTRAINT "FK_4987d9e25c0fda5d4085207f258"`);
        await queryRunner.query(`ALTER TABLE "tableaux_bord_cooperatives" DROP CONSTRAINT "FK_e0b7a0232d474bee47f5f19e807"`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" DROP CONSTRAINT "FK_ce9221534edb8e5575e47665272"`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" DROP CONSTRAINT "FK_d43414ee5d5f4f37d898016fdbe"`);
        await queryRunner.query(`ALTER TABLE "mises_en_relation" DROP CONSTRAINT "FK_7d7be9ee17e8517f77840190d81"`);
        await queryRunner.query(`ALTER TABLE "acheteurs" DROP CONSTRAINT "FK_9b21973b31b0e3e0864a50e98ed"`);
        await queryRunner.query(`ALTER TABLE "activites_exploitation" DROP CONSTRAINT "FK_c43569d09259529c86a1ad1315e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a0b884a3a9964aef2cd41fda60"`);
        await queryRunner.query(`DROP TABLE "subscription_plans"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_plans_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b2dfa8aac35d4e39389268935"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ccf973355b70645eff37774de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca1806bbc03217f7cc6a55acab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_10349f5b8d6102567c05cc1da2"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_tier_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dd1869507a16757b4f1769220a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1c9b5fb7b9f38cccddd7c5761b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c39d78e8744809ece8ca95730e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32b41cdb985a296213e9a928b5"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_paymentmethod_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05c8ddf3d99da9c01b7bdd2ecc"`);
        await queryRunner.query(`DROP TABLE "subscription_usages"`);
        await queryRunner.query(`DROP TABLE "subscription_features"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_features_featurekey_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d060a49c7f2acc9ea92bc89269"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ac85a9d120da7da0461a46df2"`);
        await queryRunner.query(`DROP TABLE "exports_donnees"`);
        await queryRunner.query(`DROP TYPE "public"."exports_donnees_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b14325a486fe68d16aa889e4d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20f8a7753c8859ff4a4ccd7850"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ceb8ddfd4ec97d405837e10c11"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cc6b96ba6911515323091fe622"`);
        await queryRunner.query(`DROP TABLE "utilisateurs"`);
        await queryRunner.query(`DROP TYPE "public"."utilisateurs_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9097c44566a3c1fc5cd5b4132c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d08be4a4e9c6eb8fcad0f1d19"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6bac423b022c9760a3fa7f403b"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f5adb7d097bce95243ad7e3e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e52cbf86d17b46f1dc80d9185b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aef1c7aef3725068e5540f8f00"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_61643486e3edc623a0eee3063d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab0c6cef42ab7886f4c324e85b"`);
        await queryRunner.query(`DROP TABLE "agents"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8280980d4dcbc2b1850d1f2c2b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85efebe43231b68512e74aa28e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d87030cbdf61dd6a74d87d1ef"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5e2bc42312ab5c8b0e29f0edfd"`);
        await queryRunner.query(`DROP TABLE "journaux_synchronisation"`);
        await queryRunner.query(`DROP TYPE "public"."journaux_synchronisation_statut_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c61ce3f5d7159e8a075bc63f46"`);
        await queryRunner.query(`DROP TABLE "enregistrements_compte"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19e85cc7ad03b8b91e7dbe9f4e"`);
        await queryRunner.query(`DROP TABLE "producteurs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d2d8bc234df52a46c6ab5b8f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99b364aba8c5ab1d6ab713b717"`);
        await queryRunner.query(`DROP TABLE "exploitations"`);
        await queryRunner.query(`DROP TYPE "public"."exploitations_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_317c1c908c017c011f4e19cac4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_81ccb763336cf43c58cbadb20d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_800dcc4afcad41ac18cd71add9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b43ea95df4570d0f4f719f4ac1"`);
        await queryRunner.query(`DROP TABLE "annonces"`);
        await queryRunner.query(`DROP TYPE "public"."annonces_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1c46d6745d3187f24d7094b65"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_45cd519fafd52e5a4a16403642"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae6e0e5110b8085d7cbf82d317"`);
        await queryRunner.query(`DROP TABLE "validations_fiches"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4987d9e25c0fda5d4085207f25"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c7a7d6d960bd8344617164dd0"`);
        await queryRunner.query(`DROP TABLE "cooperatives"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e0b7a0232d474bee47f5f19e80"`);
        await queryRunner.query(`DROP TABLE "tableaux_bord_cooperatives"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d7be9ee17e8517f77840190d8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d43414ee5d5f4f37d898016fdb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce9221534edb8e5575e4766527"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb65ea2dd19b72aadace3044fd"`);
        await queryRunner.query(`DROP TABLE "mises_en_relation"`);
        await queryRunner.query(`DROP TYPE "public"."mises_en_relation_statut_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b21973b31b0e3e0864a50e98e"`);
        await queryRunner.query(`DROP TABLE "acheteurs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c43569d09259529c86a1ad1315"`);
        await queryRunner.query(`DROP TABLE "activites_exploitation"`);
    }

}
